const router = require('koa-router')()
const controllers = require('../controllers')
router.get('/api/test', controllers.test)
router.get('/api/login', controllers.login)
// router.post('/api/login', controllers.login)
router.get('/api/user/get', controllers.user.get)
router.get('/api/user/getAll', controllers.user.getAll)
router.get('/api/menus/get', controllers.menus.get)
router.get('/api/roles/get', controllers.roles.get)
router.get('/api/goods/get', controllers.goods.get)
module.exports = router